[package]
name = "mirage"
version = "0.1.0"
authors = ["John Doneth <doneth7@gmail.com>", "Sonny Scroggin <sonny@scrogg.in>"]
edition = "2018"

[lib]
name = "mirage"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
image = "0.23"
rustler = "0.25.0"
